### ISSUE TITLE
Remove "PHPCS-scanning skipped" for now

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-ci#14]
Currently the tool outputs "PHPCS-scanning skipped" on all its reviews:

<img width="785" alt="screen shot 2017-10-18 at 13 43 59" src="https://user-images.githubusercontent.com/233434/31719156-6ea9afae-b40a-11e7-9a6f-6103ebe4faeb.png">

When we come to the initial launch, I think we should remove this line entirely. We'll be rolling out lint scanning to all repos before we get into PHPCS, and I think not having the line will make things simpler (and reduce potential lines of questioning).

**Comment by gudmdharalds** [comment]
Done 👍
