### ISSUE TITLE
Linting errors being missed

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-ci#15]
https://github.com/wpcomvip/vip-test/pull/80

A PR with three errors in the code, but only one error was picked up. Some of the errors were on a commit on the branch for the PR, and some were not.

Errors found:

https://github.com/wpcomvip/vip-test/blob/aa85f3a5e98aa232f78abf75bbb8e1e15067715d/vip-config/vip-config.php#L23

Errors not found:

https://github.com/wpcomvip/vip-test/blob/aa85f3a5e98aa232f78abf75bbb8e1e15067715d/plugins/index.php#L3

https://github.com/wpcomvip/vip-test/blob/aa85f3a5e98aa232f78abf75bbb8e1e15067715d/plugins/hello.php#L82

```
SWTBMBP:vip-test simonwheatley$ php -l vip-config/vip-config.php

Parse error: syntax error, unexpected 'is' (T_STRING) in vip-config/vip-config.php on line 23
Errors parsing vip-config/vip-config.php

SWTBMBP:vip-test simonwheatley$ php -l plugins/index.php

Parse error: syntax error, unexpected 'HAY' (T_STRING) in plugins/index.php on line 3
Errors parsing plugins/index.php

SWTBMBP:vip-test simonwheatley$ php -l plugins/hello.php

Parse error: syntax error, unexpected 'ERRAH' (T_STRING) in plugins/hello.php on line 82
Errors parsing plugins/hello.php
```

**Comment by simonwheatley** [comment]
Separate example:

https://github.com/wpcomvip/vip-test/pull/81

The above PR is from `master`, I committed a syntax error to `master` here:

https://github.com/wpcomvip/vip-test/blob/1f9dc17614abee506ab56facc4531566b928b2f9/plugins/just-wrong.php

I then branched from `master`, bringing the syntax error into the branch. I then created an innocuous commit which does nothing much:

https://github.com/wpcomvip/vip-test/commit/149f635fc2fe6c3794e3c405db54d1c040b19926

I then created a PR:

https://github.com/wpcomvip/vip-test/pull/81

TeamCity ran, and linting passed the build:

<img width="785" alt="screen shot 2017-10-18 at 14 16 08" src="https://user-images.githubusercontent.com/233434/31720607-ea159820-b40e-11e7-9ce6-2fb5b3ed001f.png">

**Comment by simonwheatley** [comment]
Another example:

https://github.com/wpcomvip/vip-test/pull/82

Three commits in a branch created locally, the first has a syntax error and the subsequent two are just code comments.

The tool submitted three reviews, none of which picked up the syntax error in the branch here:

https://github.com/wpcomvip/vip-test/blob/testing-a-multi-commit-push/plugins/ooops-i-did-it-again.php

**Comment by gudmdharalds** [comment]
This should be solved by now.
