### ISSUE TITLE
Multiple errors on one PR branch results in multiple reviews

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-ci#16]
https://github.com/wpcomvip/vip-test/pull/79

The PR above already had one syntax error, I added two more syntax errors within this commit:

https://github.com/wpcomvip/vip-test/pull/79/commits/bede84c3274902525f7e4291dd2c3bbbadf4e26d

Three reviews were added, one for each error:

* https://github.com/wpcomvip/vip-test/pull/79#pullrequestreview-69618550
* https://github.com/wpcomvip/vip-test/pull/79#pullrequestreview-69618947
* https://github.com/wpcomvip/vip-test/pull/79#pullrequestreview-69618987

One review should have been added, each of the three errors should have been referenced within the one review.

**Comment by gudmdharalds** [comment]
This functionality has been altered. Currently syntax errors are reported as generic PR comments -- and are deleted when the syntax-issues have been fixed. As for PHPCS issues, they are still submitted as PR Reviews, but they are not repeated on further scanning of later commits.
