### ISSUE TITLE
Dismiss old reviews

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-ci#24]
When a new review is posted by the bot, we should be dismissing all old reviews from the bot, so that they don't all build up as `CHANGES_REQUESTED`.

This becomes a problem on busy PRs that end up with over 30 reviews (the default page size in GH API responses), because when we query open PRs in the RQ, we're checking for an approving review from a team member - but with more than 30 open reviews, we have to start paginating through responses, which is suboptimal and wastes API requests.

Instead, the bot should auto-dismiss old reviews from itself to keep the open reviews nice and tidy. Same with any comments it makes (if it's a review comment, that _should_ get cleaned up automatically with the review).

**Comment by gudmdharalds** [comment]
Discussed this with @nickdaugherty, and we agreed that it should be enough to dismiss any reviews that have all comments `inactive` (i.e., comments are obsolete as the code has been altered). Also, changes have been made to `vip-go-ci` configuration so it will post 18 comments in one review, which should make this less of a problem.

**Comment by gudmdharalds** [comment]
This has now been implemented: https://github.com/Automattic/vip-go-ci/pull/20/files#diff-daf19feb4bb02b4eeba6bf5265591a47R942

This will be rolled out when a new version of `vip-go-ci` will be released.
