### ISSUE TITLE
Ignore build tools

### ISSUE THREAD

**Issue by philipjohn** [Automattic/vip-go-ci#28]
CI Bot currently looks at files used by build/dev tools such as Gruntfile.js. Is it worthwhile looking at these? Do we care about such files that aren't production code but a necessarily in the repo?

**Comment by gudmdharalds** [comment]
This is a known issue, and it will be addressed in a future version of `vip-go-ci`. The aim is to make use of files that have the same format as `.gitignore`.

**Comment by gudmdharalds** [comment]
#51 is similar to this, and the feature planned there will solve this.
