### ISSUE TITLE
Leave a comment if no issues found

### ISSUE THREAD

**Issue by tomjn** [Automattic/vip-go-ci#40]
If no PHPCS issues are found, no comments are left on the PR, which can leave users unsure if it's ran or not. Leaving a comment would remove the uncertainty

**Comment by gudmdharalds** [comment]
This is something `vip-go-ci` did at first, but it was later discussed and decided that it would be enough to leave a green check-mark on the build to indicate that everything was good. Most users seem to be satisfied with this.

I do agree that a comment might be a good idea. I would like to see some strong arguments for introducing it though. Let me know if you have anything in mind.

**Comment by davidsword** [comment]
I think this would be a good idea. 

The visual queue of the comment is more obvious than "All checks have passed", and it gives a nice pat on the back to the author that things look good.

**Comment by gudmdharalds** [comment]
With the optional configuration now in place, we could introduce this and allow users to turn the feature off.

**Comment by gudmdharalds** [comment]
This is resolved in #246.
