### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by mbtamuli** [Automattic/vip-go-ci#41]
Your repository is missing a license. If you need help finding a license, [ChooseALicense](https://choosealicense.com/) is a great resource.

We are experimenting on [Github Actions](https://github.com/features/actions) with [vip-go-ci](https://github.com/Automattic/vip-go-ci), so we want to be sure we are able to use it.

**Comment by gudmdharalds** [comment]
Hi!

Thanks for filing this. I've now added a license (7006a8e).
