### ISSUE TITLE
Label to have phpcs scan not run on a PR

### ISSUE THREAD

**Issue by mdbitz** [Automattic/vip-go-ci#62]
> Also, is there a way to block bot and people from reviewing? I knot there are those Status flags that would tell people not to look. But how do we stop the bot?

Clients are doing their own reviews in GH and also continually updating changes. It would be a nice feature to add a flag (label) or similar to a PR and have the bot know not to run a scan.

**Comment by gudmdharalds** [comment]
Resolved by #67.
