### ISSUE TITLE
Adjust severity level

### ISSUE THREAD

**Issue by GaryJones** [Automattic/vip-go-ci#64]
`vip-go-ci` currently runs PHPCS at `--severity=1`, which means it shows all violations.

The default severity is 5, so when someone runs PHPCS locally (and doesn't use the severity flag), they might be have no violations, but when the bot does it, they then get extra comments. This can be frustrating and confusing.

With the aim of reducing some comment noise, I wonder if we should bump the severity that the bot uses to either 3 or 5.

This would give us room to include Warnings that should show up when scanning locally, but NOT when using the bot.

**Comment by paulschreiber** [comment]
Having more warnings is helpful. If you are going to adjust the severity level of the bot, let users opt out of it (and have `severity==1` for their accounts).

**Comment by gudmdharalds** [comment]
It is possible to adjust the severity level. I think though it might be a good idea to have it adjustable via file in each repository; something like `.vipgoci_config`. Does that sound good?

**Comment by paulschreiber** [comment]
Having .vipgoci_config adjustable would be helpful.

My primary concern is that manual CLI use should, by default, show all WPCS warnings and errors (whether or not a VIPCS ruleset is enabled).

**Comment by gudmdharalds** [comment]
This will be solved by #68.

**Comment by gudmdharalds** [comment]
Pull-Request #68 has been merged.

**Comment by paulschreiber** [comment]
@gudmdharalds When will this be activated?

**Comment by gudmdharalds** [comment]
@paulschreiber: The feature has now been activated. See instructions [here](https://github.com/automattic/vip-go-ci/#configuration-via-repository-config-file).
