### ISSUE TITLE
Auto-approve PHP files with added, updated or deleted comments

### ISSUE THREAD

**Issue by gudmdharalds** [Automattic/vip-go-ci#73]
`vip-go-ci` should be able to approve PHP files with only added, updated or deleted comments. Hence, if a file is changed in this way it should be marked internally (and possibly by inline comment) as approved, and if all files in the relevant Pull-Request are approved, the Pull-Request is auto-approved in the same fashion as is done now with PHP files and other file-types.

The logic behind detecting if a PHP file has been altered in the above fashion should be as follows: `vip-go-ci` would fetch the original version of the altered file, the one used as base-commit for the relevant Pull-Request, and it would fetch the altered file as well. Then it would run [php_strip_whitespace()](https://www.php.net/manual/en/function.php-strip-whitespace.php) against the two files and calculate the SHA1 sum of both outcomes; if the sums are the same, then there was no material change to the file and it can be considered approved.

This logic would require an auto-approval scanning module of its own, similar to `ap-svg-files.php`.

**Comment by simonwheatley** [comment]
Noted in JIRA as [GH-3350]

**Comment by gudmdharalds** [comment]
Notes:
* To fetch a specific revision of a file, one can use the following command: `git show CommitID:file-path`. For instance, for the `vip-go-ci` project, the following would work: `git show b9914793c52835907c687d8685ed1b8dd1609f4b:auto-approval.php`. 
* Leave a comment for the files that are approved in this fashion, just like with hashes-to-hashes. Use a unique type though.

**Comment by gudmdharalds** [comment]
See Pull-Request #84 for implementation of this.

**Comment by gudmdharalds** [comment]
Marking this as solved; #84 has been merged.
