### ISSUE TITLE
Use local checkout from TeamCity instead of fetching files from GitHub

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-ci#8]
When TeamCity runs, it will check out the repo to the given SHA that it's running for - we should be able to use that copy of the local git repo instead of [fetching the files from GH](https://github.com/Automattic/vip-go-ci/blob/07b3e275effd29dea7ae2a3a9d98dd59cf4064cb/phpcs-scan.php#L254-L282) again.

Not totally sure how that works, but perhaps TeamCity exposes some environment variables to tell us the path to the checkout? cc @mermel

**Comment by gudmdharalds** [comment]
I worked on this a bit, but I could not find any environment-variables that seemed consistent enough to use, one would have had to rely on constants -- but maybe there is a better way to implement this.

**Comment by gudmdharalds** [comment]
Implemented in 29a902e
