### ISSUE TITLE
Docs: Add note to explain how to get hashes for tools-init.sh

### ISSUE THREAD

**Issue by GaryJones** [Automattic/vip-go-ci#95]
Please add some documentation to the top of [`tools-init.sh`](https://github.com/Automattic/vip-go-ci/blob/master/tools-init.sh), to explain exactly how to get the hashes for the tools.

I know you've told me before, but it would be useful to have this information at the point of needing it (contextual).

**Comment by gudmdharalds** [comment]
Added documentation, see #97.
