### ISSUE TITLE
Bump to WPCS 2.3.0

### ISSUE THREAD

**Issue by GaryJones** [Automattic/vip-go-ci#96]
[WordPress Coding Standards 2.3.0](https://github.com/WordPress/WordPress-Coding-Standards/releases/tag/2.3.0) has been released.

Please have the Review Bot start using it :-)

Note that [WPCS 2.2.0](https://github.com/WordPress/WordPress-Coding-Standards/releases/tag/2.2.0) was released as well previously, so the changes for that would need to be considered as well.

**Comment by gudmdharalds** [comment]
In progress, am reviewing differences between these versions.

**Comment by gudmdharalds** [comment]
Closing, is being worked on in #98
